services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    environment:
      - PYTHONUNBUFFERED=1
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - DEBUG=True
    tty: true
