# Generated by Django 6.0.6 on 2026-06-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceentry',
            options={'ordering': ['-date'], 'verbose_name_plural': 'maintenance entries'},
        ),
    ]
